#+TITLE: 学习 GNU Emacs

* 前言
Emacs 是迄今为止功能最为强大的文本编辑器.

与其他大多数编辑器的不同之处在于 Emacs 是一个完备的工作环境.

只要有一台终端, 就可以在 Emacs 环境里永不停息地工作.

如果愿意花时间,可以用它做任何你想做的事情.

** 学习本书的目的
教大家如何从最基本的东西开始去熟悉和掌握 Emacs.

** 学习 Emacs 的方法
Emacs 是一个庞大而又功能丰富的编辑器.

学习 Emacs 的最佳办法就是蚂蚁啃骨头: 先学会最基本的编辑功能, 其他功能可以等到你对它们有了兴趣或者等到你想做什么事却又不知该如何在 Emacs 里做的时候再去进一步学习.

* Emacs 的基本概念

** Emacs 简介

Emacs 的确可以把许多事情都做得很好, 不过人们并不是因为这一点才说它重要的.

Emacs 的重要性体现在 *它能把你想做的许多事情都集成到一起来* 这一点上.

就任何一种文本编辑器而言, 不管它是多么简单或者多么复杂, 其基本功能都应该是相同的. 

只要你能学会一种, 就完全能够学会它们当中的任何一种.

学习使用编辑器其实就是 *学习手指的习惯性动作*.

** 理解文件与编辑缓冲区
编辑器并不是对某个文件本身进行编辑.

事实上, 编辑器会先把文件的内容放到一个临时性的缓冲区里, 然后再对缓冲区里的东西进行编辑.

在通知编辑器保存缓冲区的内容之前, 存放在磁盘上的原始文件是不会发生任何改变的.

** 编辑模式
编辑模式使 Emacs 成为能满足你不同工作任务要求的 *专用编辑器*

一个编辑缓冲区每次只能处于一种主模式中, 退出一种主模式的办法是进入另一种主模式.

当编辑一个文件的时候, Emacs 会根据正在进行的编辑工作尝试进入正确地主模式.

有时候, Emacs 会根据文件的内容而不仅仅是文件名来做出判断.

如果它判断不出应该放到哪个编辑模式里, 就会转入基本编辑模式.

在主模式之外还有一些副模式.

副模式定义的是 Emacs 某些特定的行为, 可以在某个主模式里打开或者关闭.

如果你擅长 LISP 程序设计, 还可以自行增加新的编辑模式.

** 启动 Emacs
** Emacs 的编辑画面
一个光标将标识出你在文件里的前后位置. 这个光标也叫做 *插入点*
** Emacs 命令
每个命令都有一个正式的名字, 它们实际上是 Emacs 内部 LISP 例程的名字.

Emacs 把一个命令名与一个以 CTRL 或 ESC 打头的组合键关联起来.

命令与组合键之间的这种联系被称为 *绑定*

Emacs 允许用户自己定义组合键.
** 打开一个文件
C-x C-f <-> find-file
** 如果读入了错误的文件
C-x C-v
** Emacs 的名称自动补足功能
Emacs 有一个很有用的功能叫做 自动完成
** 插入和追加文件
如果想把一个文件插入另外一个文件, 只需要移动到文件的适当位置, 再按下 C-x i 即可.
如果想追加一个文件, 移动到文件的结尾, 然后按下 C-x i.

Emacs 会提示用户在辅助输入区里输入文件名.
** Emacs 如何确定默认目录
默认目录是根据光标当时所在的编辑缓冲区确定的.
** 保存文件
如果想保存正在编辑的文件, 请按下 C-x C-s 组合键.
** 退出 Emacs
如果想结束一次 Emacs 会话, 可以按下 C-x C-c 组合键.
** 获取帮助
C-h / C-h k/ C-h f

* 文件编辑
  :LOGBOOK:
  CLOCK: [2018-05-03 Thu 09:27]
  :END:
** 光标的移动
** 移动光标的其他方法
** 把光标一次移过一个或者多个屏显画面
C-v
** 命令的重复执行
C-u n 
** 重新绘制屏显画面
C-l
** Emacs 命令与你的键盘
建议大家记住标准的 Emacs 命令.
** 文本的删除
** 恢复已删除的文本
** 文本块及其编辑操作
** 文本的复制
** 恢复早先的删除操作
** 文本块的选取和粘贴
** 段落重排
** 编辑技巧和快捷键
*** 交换位置
*** 改变字母的大小写
*** 文本的改写模式
** 命令的中止和修改的撤销
*** 命令的中止
*** 修改的撤销
* 查找和替换操作

* 使用编辑缓冲区和窗口
Emacs 最有用的功能之一是它能够同时对多个编辑缓冲区进行编辑, 并利用窗口同时显示一个以上的编辑缓冲区.

** 文件 编辑缓冲区 窗口
Emacs 里的一切编辑操作都发生在 编辑缓冲区 里.

可以不受限制地打开任意多个编辑缓冲区.

特殊用途编辑缓冲区的创建工作由 Emacs 负责. 这些内部编辑缓冲区的名字通常采用 "*buffer name*"

每个编辑缓冲区都有一个相关的主编辑模式, 这个主编辑模式左右着 Emacs 在这个编辑缓冲区里的大部分行为.

窗口是显示器屏幕上用来显示编辑缓冲区内容的区域. 换句话说, 需要通过一个窗口来查看一个编辑缓冲区.

显示器屏幕就是一个大窗口.

每一个窗口都有一个相关的状态行, 并且通常也只有一个.

理论上讲, 可以在屏幕上不受限制地拥有任意多个不同的窗口.

** 同时使用多个编辑缓冲区进行工作
在编辑缓冲区之间进行切换需要按下 C-x b 组合键.

C-x b 特别适用于没有记住正在编辑的文件的名字的场合.

** 多个编辑缓冲区的保存
** 编辑缓冲区的删除
删除一个编辑缓冲区的方法是 C-x k 组合键.
** 编辑缓冲区的重新命名
** 只读编辑缓冲区
** 使用窗口进行编辑
*** 创建上下排列的窗口
*** 创建左右排列的窗口
*** 在窗口之间移动
*** 窗口的删除
*** 调整窗口的大小尺寸
*** 窗口大小的上下限
*** 对其他窗口进行操作的快捷命令
*** 对比两个窗口中的文件
** 查看编辑缓冲区清单
** 与编辑缓冲区清单有关的操作
** 在文档中使用书签
*** 书签的设置
*** 移动到书签指示的位置
*** 书签的重新命名和删除
*** 与书签清单有关的操作
*** 与书签有关的其他编辑命令
** 临时性地挂起 Emacs
** 使用多个 X 窗口进行编辑
Emacs 把 X 窗口称为 窗格 

*** 窗格操作命令
*** 窗格与编辑缓冲区的关系

* Emacs 工作环境

* 电子邮件和 Usenet 新闻

* Emacs 的因特网工具箱

* 简单的文字排版和特效编辑

* 用 Emacs 设置排版标记

* Emacs 中的宏

* 对 Emacs 进行定制

* 程序员的 Emacs

* 用 LISP 语言对 Emacs 做进一步开发

* Emacs 编辑器和 X 窗口系统

* Emacs 下的版本控制

* 在线帮助

* 快捷键

| Emacs   | Spacemacs |
|---------+-----------|
| C-x C-f | SPC f f   |
| C-x C-v | -         |
| C-x i   | -         |
| C-h     |           |
  
